<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
		<ApplicationIcon>Assets\macria.ico</ApplicationIcon>

		<Product>Macria</Product>
		<Version>1.7.1</Version>
		<Company>BMC</Company>
		<Authors>Enes Yeşilöz, Emre Koçak</Authors>
		<Copyright> © Macria 2026 | Tüm hakları saklıdır. </Copyright>
		<Description>CATIA / 3DEXPERIENCE montajlarındaki sac parçaları listeleyen ve DXF olarak dışa aktaran masaüstü uygulaması.</Description>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Microsoft.VisualBasic" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\macria-logo.png" />
		<Resource Include="Assets\tutorial-1.png" />
		<Resource Include="Assets\tutorial-2.png" />
		<Resource Include="Assets\tutorial-3.png" />
		<Resource Include="Assets\tutorial-4.png" />
	</ItemGroup>

</Project>